set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN T14 [get_ports led]
set_property PACKAGE_PIN F20 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]
